# buildspec_frontend.yml

version: 0.2

phases:
  install:
    commands:
      - echo "Installing required tools..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/zinclabs
  pre_build:
    commands:
      - echo "Installing dependencies..."
      # - pip3 install -r requirements.txt
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t sample-frontend-service-go -f frontend/Dockerfile .
      - docker tag sample-frontend-service-go:latest public.ecr.aws/zinclabs/sample-frontend-service-go:latest
      - docker tag sample-frontend-service-go:latest public.ecr.aws/zinclabs/sample-frontend-service-go:$CODEBUILD_BUILD_NUMBER
      - docker push public.ecr.aws/zinclabs/sample-frontend-service-go:latest
      - docker push public.ecr.aws/zinclabs/sample-frontend-service-go:$CODEBUILD_BUILD_NUMBER

