---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: hotcommerce
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: hotcommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-container
        image: public.ecr.aws/zinclabs/sample-product-service:latest
        env:
        - name: REVIEW_SERVICE_URL
          value: "http://review-service:8001"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: hotcommerce
spec:
  selector:
    app: review
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  namespace: hotcommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
      - name: review-container
        image: public.ecr.aws/zinclabs/sample-review-service:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
  namespace: hotcommerce
spec:
  selector:
    app: shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
  namespace: hotcommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop-container
        image: public.ecr.aws/zinclabs/sample-shop-service:latest
        env:
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8000"
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hotcommerce
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: hotcommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: public.ecr.aws/zinclabs/sample-frontend-service:latest
        env:
        - name: SHOP_SERVICE_URL
          value: "http://shop-service:8002"
        ports:
        - containerPort: 8080
