# buildspec_shop.yml

version: 0.2

phases:
  install:
    commands:
      - echo "Installing required tools..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/zinclabs
  pre_build:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building Docker image..."
      # - cd shop
      - docker build -t sample-shop-service-nodejs -f shop/Dockerfile .
      - docker tag sample-shop-service-nodejs:latest public.ecr.aws/zinclabs/sample-shop-service-nodejs:latest
      - docker tag sample-shop-service-nodejs:latest public.ecr.aws/zinclabs/sample-shop-service-nodejs:$CODEBUILD_BUILD_NUMBER
      - docker push public.ecr.aws/zinclabs/sample-shop-service-nodejs:latest
      - docker push public.ecr.aws/zinclabs/sample-shop-service-nodejs:$CODEBUILD_BUILD_NUMBER

